version: "3.8"

services:
  exporter:
    build: ./exporter
    container_name: usuarios_exporter
    ports:
      - "8000:8000"
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_sim
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - prometheus-net
    depends_on:
      - prometheus

networks:
  prometheus-net:
    driver: bridge
